#!/bin/bash -e

echo "Installing Oracle InstantClient Basic/SDL/SQLPlus..."
mkdir -p /tmp/oracle
cd /tmp/oracle
wget -q "https://s3.amazonaws.com/pkgr-public/instantclient-basic-linux.x64-12.1.0.2.0.zip"
wget -q "https://s3.amazonaws.com/pkgr-public/instantclient-sdk-linux.x64-12.1.0.2.0.zip"
wget -q "https://s3.amazonaws.com/pkgr-public/instantclient-sqlplus-linux.x64-12.1.0.2.0.zip"
unzip *.zip
cd instantclient_12_1
ln -s libclntsh.so.12.1 libclntsh.so
